ktor:
    application:
        modules:
            - example.com.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  audience: "jwt-audience"
#  domain: "https://jwt-provider-domain/"
  issuer: "http://localhost"
  realm: "ktor sample app"
  secret: "secret"
#  ${JWT_SECRET}


